adm/urls.py
from django.urls import path
from .views import  CargoListView, add_adotante, add_tipodespesa,RelListView,MaioAniListView,JunhoAniListView, RelAnimaisListView, MaioListView, JunhoListView, despesa_update, despesa_delete, cargo_update, despesa_detalhes, add_despesas, TipoDespesaListView, cargo_delete, add_cargo, add_funcionario, adm, DespesasListView, AnimaisListView, FuncListView, VoluntariosListView, add_doacao, DoacaoListView,doacao_update, doacao_delete,  add_voluntarios, func_update, voluntarios_delete, voluntarios_update, add_duvidas, user_update, user_delete, adotante_update, duvidas_delete, add_sobre, duvidas_update, sobre_update, sobre_delete, adotante_delete,  raca_update,  tipo_update, add_raca, raca_delete, add_animal, add_tipo, post_delete, tipo_delete, post_update, TipoListView, RacaListView, AdotanteListView, UsersListView, signup, SobreListView, DuvidasListView
from django.contrib.auth import views as auth_views

app_name = 'adm'

urlpatterns = [
    path('gerenciador/', adm.as_view(), name='gerenciador'),
    path('cad-aninal/', adm.as_view(), name='cad-animal'),
    path('animais/', AnimaisListView, name='list-animais'),
    path('editar/', adm.as_view, name='editar'),
    path('funcionarios/', FuncListView, name='funcionarios'),
    path('rel/animais/', RelAnimaisListView, name='animais'),
    path('rel/animais/maio/', MaioAniListView, name='maio'),
    path('rel/animais/junho/', JunhoAniListView, name='junho'),
    path('rel/despesas/', RelListView, name='despesas'),
    path('rel/despesas/maio/', MaioListView, name='maio'),
    path('rel/despesas/junho/', JunhoListView, name='junho'),
    path('despesas/', DespesasListView, name='despesas'),
    path('despesas/adicionar/', add_despesas, name='registrar'),
    path('despesas/editar/<int:id>/', despesa_update, name='editar'),
    path('despesas/delete/<int:id>/', despesa_delete, name='editar'),
    path('despesas/tipo/', TipoDespesaListView, name='tipo'),
    path('despesas/tipo/adicionar/', add_tipodespesa, name='registrar'),
    path('despesas/detalhes/<int:id>/', despesa_detalhes, name='detalhes'),
    path('funcionarios/adicionar/', add_funcionario, name='registrar'),
    path('funcionarios/editar/<int:id>/', func_update, name='editar'),
    path('cargo/', CargoListView, name='cargo'),
    path('cargo/adicionar/', add_cargo, name='registrar'),
    path('cargo/delete/<int:id>/', cargo_delete, name='delete'),
    path('cargo/editar/<int:id>/', cargo_update, name='editar'),
    path('animais/tipo/', TipoListView, name='tipo'),
    path('animais/raca/', RacaListView, name='raca'),
    path('animais/adotante/', AdotanteListView, name='adotante'),
    path('usuarios/', UsersListView, name='usuarios'),
    path('animais/sobre/', SobreListView, name='sob'),
    path('animais/duvidas/', DuvidasListView, name='duvidas'),
    path('voluntarios/adicionar/', add_voluntarios, name='registrar'),
    path('voluntarios/', VoluntariosListView, name='voluntarios'),
    path('voluntarios/editar/<int:id>/', voluntarios_update, name='editar'),
    path('voluntarios/delete/<int:id>/', voluntarios_delete, name='delele'),
    path('doacao/', DoacaoListView, name='doacao'),
    path('doacao/editar/<int:id>/', doacao_update, name='editar'),
    path('doacao/adicionar/', add_doacao, name='adicionar'),
    path('doacao/delete/<int:id>/', doacao_delete, name='delele'),
    path('usuarios/registrar/', signup, name='registrar'),
    path('animais/adicionar/', add_animal, name='adicionar'),
    path('usuarios/editar/<int:id>/', user_update, name='editar'),
    path('usuarios/delete/<int:id>/', user_delete, name='delele'),
    path('animais/editTodo/<int:id>/',post_update, name='editTodo'),
    path('animais/tipo/adicionar/', add_tipo, name='add_tipo'),
    path('animais/delete/<int:id>/', post_delete, name='delete'),
    path('animais/adotante/adicionar/', add_adotante, name='add_tipo'),
    path('animais/adotante/editar/<int:id>/', adotante_update, name='editar'),
    path('animais/adotante/delete/<int:id>/', adotante_delete, name='delete'),
    path('animais/sobre/editar/<int:id>/', sobre_update, name='editar'),
    path('animais/sobre/delete/<int:id>/', sobre_delete, name='delete'),
    path('animais/sobre/adicionar/', add_sobre, name='add_sobre'),
    path('animais/raca/adicionar/', add_raca, name='add_raca'),
    path('animais/duvidas/delete/<int:id>/', duvidas_delete, name='delete'),
    path('animais/duvidas/adicionar/', add_duvidas, name='add_duvidas'),
    path('animais/duvidas/editar/<int:id>/', duvidas_update, name='editar'),
    path('animais/raca/editar/<int:id>/', raca_update, name='editar'),
    path('animais/raca/delete/<int:id>/', raca_delete, name='delete'),
    path('animais/tipo/edittipo/<int:id>/',tipo_update, name='edittipo'),
    path('animais/tipo/delete/<int:id>/', tipo_delete, name='delete')
]

blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:slug>', views.post_detail, name='post_detail'),
    path('criar/', views.post_create, name='post_create'),
    path('editar/<int:id>/', views.post_update, name='post_update'),
    path('deletar/<int:id>/', views.post_delete, name='post_delete'),
    path('sobre-nos/', views.about, name='about'),
    path('contato/', views.contact, name='contact'),
    path('parceiros/', views.parceiros, name='parceiros'),
    path('duvidas/', views.duvidas, name='duvidas'),
    path('voluntarios/', views.voluntarios, name='voluntarios'),
    path('duvidas-voluntarios/', views.duvidas_voluntario, name='duvidas_voluntario'),
    path('form-voluntarios/', views.form_voluntario, name='form_voluntario'),
    path('pagina-responsabilidades/', views.page_responsabilidades, name='page_responsabilidades'),
    
]

meuprojeto/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('animais/', include('animais.urls')),
    path('doacao/', include('doacao.urls')),
    path('adocao/', include('adocao.urls')),
    path('adm/', include('adm.urls')),
    path('account/', include('django.contrib.auth.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User



class Post (models.Model):
    STATUS = (
    ('active', 'Ativo'),
    ('draft', 'Rascunho')
    )
    title = models.CharField(max_length=200, verbose_name='Título')
    slug = models.SlugField()
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Autor')
    created_at = models.DateField(auto_now_add=True, verbose_name='criado em')
    updated_at = models.DateField(auto_now=True, verbose_name='atualizado em')
    status = models.CharField(max_length=15, choices=STATUS)

    def __str__(self):
     return self.title

class TipoAnimal(models.Model):
    TipoAnimal = models.CharField(max_length=20, verbose_name='Tipo de Animal')
    def __str__(self):
        return self.TipoAnimal
    class Meta:
            verbose_name_plural = "Tipos de Animais"

        
class RacaAnimal(models.Model):
    TipoAnimal = models.ForeignKey(TipoAnimal, on_delete=models.CASCADE, verbose_name='Tipo de Animal')
    RacaAnimal = models.CharField(max_length=30, verbose_name='Raça do Animal')
    def __str__(self):
        return self.RacaAnimal
    class Meta:
            verbose_name_plural = "Raças"

class Animais(models.Model):
    OPCAO = (
    ('Sim', 'Sim'),
    ('Não', 'Não')
    )
    Sexo = (
    ('Macho', 'Macho'),
    ('Femea', 'Femea')
    )
    NomeAnimal = models.CharField(max_length=80, verbose_name='Nome do Animal')
    IdadeAnimal = models.CharField(max_length=10, verbose_name='Idade aproxima do Animal')
    TipoAnimal = models.ForeignKey(TipoAnimal, on_delete=models.CASCADE, verbose_name='Tipo de Animal') 
    RacaAnimal = models.ForeignKey(RacaAnimal, on_delete=models.CASCADE, verbose_name='Raça do Animal') 
    PesoAnimal = models.CharField(max_length=5, verbose_name='Peso do Animal')
    CorAnimal = models.CharField(max_length=15, verbose_name='Cor do Animal')
    SexoAnimal = models.CharField(max_length=15, choices=Sexo, verbose_name='Sexo do Animal')
    Vacinado = models.CharField(max_length=15, choices=OPCAO, verbose_name='Vacinado?')
    Adotado = models.CharField(max_length=15, choices=OPCAO, verbose_name='Adotado?')
    FotoCapaAnimal = models.ImageField(upload_to='media/', null=True, verbose_name='Foto de Capa')
    Observacao = models.TextField(null=False, verbose_name='Observação')
    ativo = models.BooleanField(default=True)
    def __str__(self):
        return self.NomeAnimal
    
    class Meta:
            verbose_name_plural = "Animais"

    

blog/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'body', 'author', 'status']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core.paginator import Paginator
from .models import Post
from .forms import PostForm
# Create your views here.


def post_list(request):
    post_list = Post.objects.all().order_by('-created_at')
    paginator = Paginator(post_list, 3)

    page = request.GET.get('page')
    posts = paginator.get_page(page)
    return render(request, 'blog/post_list.html', {'posts':posts})

def about(request):
 return render(request, 'blog/about_us.html')

def doacao(request):
     return render(request, 'blog/doacao.html')

def adocao(request):
     return render(request, 'blog/adocao.html')

def parceiros(request):
     return render(request, 'blog/parceiros.html')

def duvidas(request):
     return render(request, 'blog/duvidas.html')

def voluntarios(request):
     return render(request, 'blog/voluntarios.html')

def form_voluntario(request):
     return render(request, 'blog/form_voluntario.html')

def duvidas_voluntario(request):
     return render(request, 'blog/duvidas_voluntario.html')

def page_responsabilidades(request):
     return render(request, 'blog/page_responsabilidades.html')

@login_required
def administrativo(request):
     return render(request, 'blog/administrativo.html')


def contact(request):
 return render(request, 'blog/contact.html')

def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    return render(request, 'blog/post_detail.html', {'post':post})

@login_required
def post_create(request):
    form = PostForm()

    if(request.method == 'POST'):

        form = PostForm(request.POST)

        if(form.is_valid()):
            post_title = form.cleaned_data['title']
            post_slug = form.cleaned_data['slug']
            post_body = form.cleaned_data['body']
            post_author = form.cleaned_data['author']
            post_status = form.cleaned_data['status']

            new_post = Post(title=post_title, slug=post_slug, body=post_body, author=post_author, status=post_status)
            new_post.save()

            return redirect('blog:post_list')

    elif(request.method == 'GET'):
        return render(request, 'blog/add_post.html', {'form': form})

@login_required
def post_update(request, id):
    post = get_object_or_404(Post, pk=id)
    form = PostForm(instance=post)

    if(request.method == 'POST'):
        form = PostForm(request.POST, instance=post)
        
        if(form.is_valid()):
            post = form.save(commit=False)
            post.title = form.cleaned_data['title']
            post.description = form.cleaned_data['slug']
            post.body = form.cleaned_data['body']
            post.author = form.cleaned_data['author']
            post.status = form.cleaned_data['status']

            post.save()

            return redirect('blog:post_list')
        else:
            return render(request, 'blog/edit_post.html', {'form': form, 'post' : post})

    elif(request.method == 'GET'):
        return render(request, 'blog/edit_post.html', {'form': form, 'post' : post})

@login_required
def post_delete(request, id):
    post = get_object_or_404(Post, pk=id)
    post.delete()
    return redirect('blog:post_list')

blog/templates/blog/about-us.html
{% extends 'blog/base.html' %}
{% block title %}Título do post{% endblock %}

{% block content %}
    <h1>Sobre nós</h1>
    <p>Esta é a história do blog...</p>
{% endblock %}

blog/templates/blog/add_post.html
{% extends 'painel-adm.html' %}
{% load bootstrap %}
{% block title %}Adicionar um post{% endblock %}

{% block content %}
    <div class="container">
        <h1>Adicionar um post</h1>
        <div>
            <form action="." method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|bootstrap }}
                <input type="submit" class="btn btn-default" value="Criar">
            </form>
            
        </div>
    </div>
{% endblock %}

blog/templates/blog/baseold.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

	  <!-- Vendor CSS Files -->
	  <link href="{% static 'css/aos.css' %}" rel="stylesheet">
	  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	  <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet">
	  <link href="{% static 'css/boxicons.min.css' %}" rel="stylesheet">
	  <link href="{% static 'css/glightbox.min.css' %}" rel="stylesheet">
	  <link href="{% static 'css/swiper-bundle.min.css' %}" rel="stylesheet">
	

	 <!-- Google Fonts -->
	 <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
</head>
<body>
	  <!-- ======= Top Bar ======= -->
	  
		<div class="container d-flex justify-content-center justify-content-md-between">
		  <div class="contact-info d-flex align-items-center">
			<i class="bi bi-envelope d-flex align-items-center"><a href="mailto:contact@example.com">contact@example.com</a></i>
			<i class="bi bi-phone d-flex align-items-center ms-4"><span>+1 5589 55488 55</span></i>
		  </div>
		  <div class="social-links d-none d-md-flex align-items-center">
			<a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
			<a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
			<a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
			<a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
		  </div>
		</div>
	  
	<nav class="navbar navbar-expand-lg navbar-light">
	  <a class="navbar-brand" href="{% url 'blog:post_list' %}">Blog</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNav">
	    <ul class="navbar-nav">
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'blog:about' %}">Sobre nós</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'blog:contact' %}">Contato</a>
				</li>
				{% if user.is_authenticated %}
				<li class="nav-item">
						<a class="nav-link" href="{% url 'logout' %}">Sair</a>
				</li>
				{% else %}
				
				<li class="nav-item">
					
						<a class="nav-link" href="{% url 'login' %}">Login</a>
				</li>
				{% endif %}
	    </ul>
	  </div>
	</nav>
    <div class="row">
				{% if user.is_authenticated %}
					<p class="logged-in-p">
						Olá {{ user.username }} seja bem vindo, o que deseja fazer hoje? 
						<span class="sair"><a href="{% url 'logout' %}">Sair</a></span>
					</p>
					<div class="submenu-auth">
							<span><a href="{% url 'blog:post_create' %}">Adicionar post</a></span>
					</div>
				{% endif %}
        {% block content %}
        {% endblock %}
		</div>
		<footer>
			<span class="copy">&copy; Copyright 209, Django blog</span>
		</footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
<script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% block title %}Título do post{% endblock %}

{% block content %}
    <h1>Quer entrar em contato conosco?</h1>
{% endblock %}

blog/templates/blog/edit_post.html
{% extends 'blog/base.html' %}
{% load bootstrap %}
{% block title %}Editar '{{post.title}}'{% endblock %}

{% block content %}
    <div class="container">
        <h1>Editar '{{post.title}}'</h1>
        <div class="form-group col-md-6 mb-0">
            <form action="." method="POST">
                {% csrf_token %}
                {{ form|bootstrap }}
                <input type="submit" class="btn btn-default" value="Editar">
            </form>
        </div>
        <hr>
        <form action="{% url 'blog:post_delete' post.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value='Deletar post'>
        </form>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="container">
        <h1>{{ post.title }}</h1>
        <p>Publicado em {{ post.created_at }} por {{ post.author }}</p>
        <p>{{ post.body|linebreaks }}</p>
    </div> 
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block title %}Listagem de Posts{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron jumbotron-fluid">
          <div class="container">
            <h1 class="display-4">Bem vindo ao Django blog!</h1>
            <p class="lead">Aqui você vai encontrar os melhores posts sobre o framework.</p>
          </div>
        </div>
        <div class="row">
                            {% for post in posts %}
                <div class="card mb-3" style="max-width: 540px;">
                  <div class="row g-0">
                    <div class="col-md-4">
                      <img src="https://via.placeholder.com/286x180" class="img-fluid rounded-start" alt="...">
                    </div>
                    <div class="col-md-8">
                      <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">{{ post.body|truncatechars:50 }}...</p>
                        <p class="card-text"><small class="text-muted">Criado em {{ post.created_at }} por {{ post.author }}</small></p>
                        <a href="{% url 'blog:post_detail' post.slug %}" class="btn btn-primary">Ver o post completo</a>
                      </div>
                    </div>
                  </div>
                </div>
                
                {% endfor %}
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href="?page={{ posts.previous_page_number }}">Anterior</a>
                {% endif %}
            
                <span class="current">
                    {{ posts.number }} de {{ posts.paginator.num_pages }}
                </span>
            
                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}">Próxima</a>
                {% endif %}
            </span>
        </div>
    </div> 
{% endblock %}

blog/templates/blog/tipo-animais.html
{% extends 'blog/administrativo.html' %}
{% load bootstrap %}
{% block title %}Adicionar um post{% endblock %}

{% block content %}
    <div class="container">
        <h1>Adicionar um post</h1>
        <div>
            <form action="." method="POST">
                {% csrf_token %}
                {{ form|bootstrap }}
                <input type="submit" class="btn btn-default" value="Criar">
            </form>
            
        </div>
    </div>
{% endblock %}